#  ./mvnw clean package -Dspring.profiles.active=test
#docker-compose up -d
#docker ps
#docker start {id}

#Ao conectar ao banco, use o port 5433

services:
  postgres:
    image: postgres
    container_name: pharmaphorma-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: pharmaphorma
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - pharmacy-net

#  spring-app:
#    build: .
#    container_name: pharmaphorma-app
#    ports:
#      - "8081:8081"
#    depends_on:
#      - postgres
#    networks:
#      - pharmacy-net
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/pharmaphorma
#      SPRING_DATASOURCE_USERNAME: admin
#      SPRING_DATASOURCE_PASSWORD: admin

volumes:
  pgdata:

networks:
  pharmacy-net:
